id: P64F65A2A
initial_creation_type: input
source_metadata:
  title: Drāmiḍāvidyārājā
  language: en
  volumes:
    1180d001893d4a4c87b57fe702f53d44:
      title: Colophon
      base_file: Colophon.txt
      work_id: WE4595155
    f0a28fca278841bf81fb55c80ddfba79:
      title: DHARAṆĪPADA OF ŚAKRA DEVĀNĀMINDRA
      base_file: DHARAṆĪPADA OF ŚAKRA DEVĀNĀMINDRA.txt
      work_id: W1A471ACC
    84ab1a8c6ce04d1492c25fbe33d89844:
      title: DHĀRAṆĪPADA OF GUHYAPATI VAJRAPĀṆI
      base_file: DHĀRAṆĪPADA OF GUHYAPATI VAJRAPĀṆI.txt
      work_id: WF1DF2549
    b3791eb913bf4e49a3915d5102d46ef6:
      title: Preface
      base_file: Preface.txt
      work_id: W3C01FC01
    e211c2d0282643899899f3688aba13e5:
      title: THE DHARAṆĪMANTRAPADA OF THE FOUR GREAT KINGS
      base_file: THE DHARAṆĪMANTRAPADA OF THE FOUR GREAT KINGS.txt
      work_id: WB967EBE2
    b45bf4ba14f641ae816b5fa63c3bdcff:
      title: THE DHĀRAṆĪMANTRAPADA OF BRAHMĀ SAHAMPATI
      base_file: THE DHĀRAṆĪMANTRAPADA OF BRAHMĀ SAHAMPATI.txt
      work_id: W77824EFF
    03d6c17e7117436baa60b464e55e3b63:
      title: THE MANTRA SPOKEN BY ĀRYA AVALOKITEŚVARA
      base_file: THE MANTRA SPOKEN BY ĀRYA AVALOKITEŚVARA.txt
      work_id: W52715DCE
    1fc7c00a621b4152add0139ca5121b82:
      title: THE NĀGA KINGS
      base_file: THE NĀGA KINGS.txt
      work_id: W23F91951
    bdf376c9cc6b468fb6e53d0517dd7642:
      title: Title
      base_file: Title.txt
      work_id: W5D32263D
  chapter_to_tile: {}
created_at: '2022-03-01T21:23:01.531771'
last_modified_at: '2022-03-01T21:23:01.531785'
